kind: Service #https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-mapping-external-services
apiVersion: v1
metadata:
  name: mysqlservice
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysqlservice
subsets:
  - addresses:
      - ip: 10.116.32.3 #GKE specific
    ports:
      - port: 3306